// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateUserTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createUser() {
    driver.get("http://eaapp.somee.com/");
    driver.manage().window().setSize(new Dimension(945, 1012));
    driver.findElement(By.id("loginLink")).click();
    driver.findElement(By.id("UserName")).click();
    driver.findElement(By.id("UserName")).sendKeys("admin");
    driver.findElement(By.id("Password")).sendKeys("password");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Employee List")).click();
    driver.findElement(By.linkText("Create New")).click();
    driver.findElement(By.id("Name")).click();
    driver.findElement(By.id("Name")).sendKeys("newuser");
    driver.findElement(By.id("Salary")).sendKeys("1");
    driver.findElement(By.id("DurationWorked")).sendKeys("24");
    driver.findElement(By.id("Grade")).click();
    {
      WebElement dropdown = driver.findElement(By.id("Grade"));
      dropdown.findElement(By.xpath("//option[. = 'Senior']")).click();
    }
    driver.findElement(By.id("Email")).click();
    driver.findElement(By.id("Email")).sendKeys("myemail@gmail.com");
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
